#############################################################################
# Makefile for building: MultiParallelAgent
# Generated by qmake (2.01a) (Qt 4.6.2) on: Thu Nov 11 13:42:46 2010
# Project:  MultiParallelAgent.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile MultiParallelAgent.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -fopenmp -lm -Wall -Wextra -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/local/include/gnuplot-iostream -I/usr/include/boost/iostreams -I/usr/include/boost/numeric/ublas -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -fopenmp -lm -lboost_iostreams-mt -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Main.cpp \
		Controllers/IcoSiso.cpp \
		Filters/LowPassFilter.cpp \
		World/Coordinate2D.cpp \
		Agents/DiskAgent.cpp \
		World/Steppable.cpp \
		World/World2DCartesian.cpp \
		World/velocityvector2d.cpp \
		World/geometry/RectangularBox.cpp \
		World/geometry/CircularBox.cpp \
		Logger/CSVExporter.cpp \
		World/simparameters.cpp 
OBJECTS       = Main.o \
		IcoSiso.o \
		LowPassFilter.o \
		Coordinate2D.o \
		DiskAgent.o \
		Steppable.o \
		World2DCartesian.o \
		velocityvector2d.o \
		RectangularBox.o \
		CircularBox.o \
		CSVExporter.o \
		simparameters.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		MultiParallelAgent.pro
QMAKE_TARGET  = MultiParallelAgent
DESTDIR       = 
TARGET        = MultiParallelAgent

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MultiParallelAgent.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile MultiParallelAgent.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile MultiParallelAgent.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/MultiParallelAgent1.0.0 || $(MKDIR) .tmp/MultiParallelAgent1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MultiParallelAgent1.0.0/ && $(COPY_FILE) --parents LowPassFilter.h Controllers/IcoSiso.h Filters/LowPassFilter.h World/Coordinate2D.h Agents/DiskAgent.h World/Steppable.h World/World2DCartesian.h Test/TestRoutines.h Entropy/SampleSetWriter.h Entropy/SampleSetReader.h Entropy/Entropy.h Entropy/AleatoryVariable.h Entropy/include/Entropy.h Entropy/include/AleatoryVariable.h Entropy/include/JointVariable.h Logger/CSVDatabase.h Entropy/include/Histogram.h MatrixUtil/MatrixOperations.h Logger/CSVExporter.h World/velocityvector2d.h World/geometry/RectangularBox.h World/geometry/CircularBox.h World/simparameters.h .tmp/MultiParallelAgent1.0.0/ && $(COPY_FILE) --parents Main.cpp Controllers/IcoSiso.cpp Filters/LowPassFilter.cpp World/Coordinate2D.cpp Agents/DiskAgent.cpp World/Steppable.cpp World/World2DCartesian.cpp World/velocityvector2d.cpp World/geometry/RectangularBox.cpp World/geometry/CircularBox.cpp Logger/CSVExporter.cpp World/simparameters.cpp .tmp/MultiParallelAgent1.0.0/ && (cd `dirname .tmp/MultiParallelAgent1.0.0` && $(TAR) MultiParallelAgent1.0.0.tar MultiParallelAgent1.0.0 && $(COMPRESS) MultiParallelAgent1.0.0.tar) && $(MOVE) `dirname .tmp/MultiParallelAgent1.0.0`/MultiParallelAgent1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MultiParallelAgent1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

Main.o: Main.cpp World/World2DCartesian.h \
		Logger/CSVExporter.h \
		Agents/DiskAgent.h \
		World/Steppable.h \
		World/Coordinate2D.h \
		World/velocityvector2d.h \
		World/geometry/RectangularBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o Main.cpp

IcoSiso.o: Controllers/IcoSiso.cpp Controllers/IcoSiso.h \
		Filters/LowPassFilter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IcoSiso.o Controllers/IcoSiso.cpp

LowPassFilter.o: Filters/LowPassFilter.cpp Filters/LowPassFilter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LowPassFilter.o Filters/LowPassFilter.cpp

Coordinate2D.o: World/Coordinate2D.cpp World/Coordinate2D.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Coordinate2D.o World/Coordinate2D.cpp

DiskAgent.o: Agents/DiskAgent.cpp Agents/DiskAgent.h \
		World/Steppable.h \
		World/Coordinate2D.h \
		World/velocityvector2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DiskAgent.o Agents/DiskAgent.cpp

Steppable.o: World/Steppable.cpp World/Steppable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Steppable.o World/Steppable.cpp

World2DCartesian.o: World/World2DCartesian.cpp World/World2DCartesian.h \
		Logger/CSVExporter.h \
		Agents/DiskAgent.h \
		World/Steppable.h \
		World/Coordinate2D.h \
		World/velocityvector2d.h \
		World/geometry/RectangularBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o World2DCartesian.o World/World2DCartesian.cpp

velocityvector2d.o: World/velocityvector2d.cpp World/velocityvector2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o velocityvector2d.o World/velocityvector2d.cpp

RectangularBox.o: World/geometry/RectangularBox.cpp World/geometry/RectangularBox.h \
		World/Coordinate2D.h \
		Agents/DiskAgent.h \
		World/Steppable.h \
		World/velocityvector2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RectangularBox.o World/geometry/RectangularBox.cpp

CircularBox.o: World/geometry/CircularBox.cpp World/geometry/CircularBox.h \
		World/Coordinate2D.h \
		Agents/DiskAgent.h \
		World/Steppable.h \
		World/velocityvector2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CircularBox.o World/geometry/CircularBox.cpp

CSVExporter.o: Logger/CSVExporter.cpp Logger/CSVExporter.h \
		Agents/DiskAgent.h \
		World/Steppable.h \
		World/Coordinate2D.h \
		World/velocityvector2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CSVExporter.o Logger/CSVExporter.cpp

simparameters.o: World/simparameters.cpp World/simparameters.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simparameters.o World/simparameters.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

